name: example-environment
channels:
  - conda-forge
dependencies:
  - h3-py
  - folium
  - shapely
  - geopandas
  - pandas
  - matplotlib
  - mapclassify
  - descartes
  - pip
  - pip:
    - pyrosm
